services:
  db:
    container_name: art-database
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
    networks:
      - fullstack
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: art_api
    build: .
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8000:8000"
    depends_on:
        db:
          condition: service_healthy
    networks:
      - fullstack
volumes:
  pgdata: {}

networks:
  fullstack:
    driver: bridge