version: '3'

tasks:
  build-local:
    cmds:
      - go build -o app cmd/server/main.go
  build-api:
    cmds:
      - docker compose up api --build
  build-db:
    cmds:
      - docker compose up db --build
  test:
    cmds:
      - go test -v ./...
  lint:
    cmds:
      - golangci-lint run
  run:
    cmds:
      - docker-compose up --build
  run-db:
    cmds:
    - docker-compose up db -d
  run-app:
    cmds:
    - docker-compose up api -d
      