version: '3'

tasks:
  build-local:
    cmds:
      - go build -o app.exe cmd/server/main.go
      - ./app.exe
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_TABLE: postgres
      DB_HOST: localhost
      DB_DB: postgres
      DB_PORT: 5432
      SSL_MODE: disable 
  build-api:
    cmds:
      - docker compose up api --build
  build-db:
    cmds:
      - docker compose up db --build
  test:
    cmds:
      - go test -v ./...
  lint:
    cmds:
      - golangci-lint run
  run:
    cmds:
      - docker-compose up --build
  run-db:
    cmds:
    - docker-compose up db -d
  run-app:
    cmds:
    - docker-compose up api -d
  integration-test:
    cmds:
      - docker-compose up -d db
      - go test -tags=integration -v ./...
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_TABLE: postgres
      DB_HOST: localhost
      DB_DB: postgres
      DB_PORT: 5432
      SSL_MODE: disable

      